FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    libxerces-c-dev \
    libmysqlclient-dev \
    liblua5.1-dev \
    psmisc \
    gcc \
    build-essential \
    xutils-dev \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /home/darkeden
RUN mkdir /home/darkeden/vs
#RUN mkdir /home/darkeden/vs/src

COPY bin /home/darkeden/vs/bin/
COPY docker/conf /home/darkeden/vs/conf/
COPY data /home/darkeden/vs/data/
COPY initdb /home/darkeden/vs/initdb/
COPY src /home/darkeden/vs/src/

WORKDIR /home/darkeden/vs/bin